server:
  port: 8084
spring:
  application:
    name: "API_GATEWAY"
  cloud:
    gateway:
      routes:
      - id: EMPLOYEE-SERVICE
        uri: lb://EMPLOYEE-SERVICE/
        predicates:
        - Path=/Employee/**  
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE/
        predicates:
        - Path=/Department/**,/Location/**
      - id: WORKS-ON-SERVICE
        uri: lb://WORKS-ON-SERVICE/
        predicates:
        - Path=/WorksOn/**  
     
  
 
eureka:
   instance:
      prefer-ip-address: true
   client:
      registerWithEureka: true
      fetchRegistry: true
      service-url:
         defaultZone: http://localhost:8761/eureka


         


