server:
  port: 8082
spring:
  application:
    name: "DEPARTMENT-SERVICE"
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/department
    username: root
    password: vardhan
  
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
eureka:
   instance:
      prefer-ip-address: true
   client:
      registerWithEureka: true
      fetchRegistry: true
      service-url:
         defaultZone: http://localhost:8761/eureka
         



